### ISSUE TITLE
You could use ampersand-state instead of model

### ISSUE THREAD

**Issue by HenrikJoreteg** [zeropaper/files-collection#2]
Hey, this is a really cool and clever use of ampersand stuff! I love that about modular code, people find awesome, unexpected ways to use it.

One suggestion would be that you could just use ampersand-state where you're currently using ampersand-model. It's the same code but model extends state with a few methods and dependencies that are for persisting models via Ajax to a server which don't look like they're being used here.

Anyway, cool stuff! Might be cool to see a few usage examples in the docs too.

Cheers!

**Comment by zeropaper** [comment]
Thanks a lot for the feedback!

Actually.. I was wondering if I should have use states instead of models.

On the other hand, I could imagine a special "sync" to actually CRUD on file system (in node.js) and CRUD over a RESTful API when in the browser.
Probably going to look at that further when I have a bit of time.

About the examples and docs.
I first made that set of classes.. to generate documentation. So obviously, it's going to happen.

Cheers and thanks again!
